### ISSUE TITLE
Deserialization fails when using `enumConverterNumeric`

### ISSUE THREAD

**Issue by caneva20** [k-paxian/dart-json-mapper#117]
Hi @k-paxian!

So, given the following models:

```dart
@jsonSerializable
enum MyEnumA {
  first, second
}

@jsonSerializable
enum MyEnumB {
  foo, bar
}

@jsonSerializable
class MyClass {
  MyEnumA enumA;
  MyEnumB enumB;

  MyClass(this.enumA, this.enumB);
}
```
I get the following error when trying to deserialize it:

```shell
E/flutter ( 6469): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'MyEnumA' is not a subtype of type 'MyEnumB'
E/flutter ( 6469): #0      _data.<anonymous closure>.<anonymous closure> (package:redacted/main.mapper.g.dart:103:377)
E/flutter ( 6469): #1      Function._apply (dart:core-patch/function_patch.dart:11:30)
E/flutter ( 6469): #2      Function.apply (dart:core-patch/function_patch.dart:34:12)
E/flutter ( 6469): #3      ClassMirrorBase.newInstance (package:reflectable/src/reflectable_builder_based.dart:655:21)
E/flutter ( 6469): #4      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:872:18)
E/flutter ( 6469): #5      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:58:21)
E/flutter ( 6469): #6      main (package:redacted/main.dart:46:24)
E/flutter ( 6469): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 6469): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 6469): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 6469): #10     _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 6469): #11     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 6469): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 6469): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 6469): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

This happens when using the `enumConverterNumeric`, the process works fine without it. I'm not sure if this happens when using other converters.

I started to face this problem when upgrading from `1.7.4` to `1.7.11`. By trying different versions (using dependency overrides) I was able to narrow the problem down to `1.7.6`, but it still happens in the latest (1.7.11) version.

**Comment by k-paxian** [comment]
Wow, thank you so much for reporting this case. That was unobvious bug with converted values caching mechanism. 
Converted values for `MyEnumA` were reused for `MyEnumB` as well, which is not accurate in terms of different enum types.

Has nothing to do with `enumConverterNumeric` itself, this converter produces ints which were cached w/o type information correlation.

Should be ok in `1.7.12`
