### ISSUE TITLE
Serialization fails with enums w/o a default value when using `enumConverterNumeric`

### ISSUE THREAD

**Issue by caneva20** [k-paxian/dart-json-mapper#118]
Hello again @k-paxian!

With the following models:

```dart
@jsonSerializable
enum MyEnum {
  first, second
}

@jsonSerializable
class MyClass {
  MyEnum myEnum;
}
```

serialization fails if you don't set a value for `myEnum`.

```dart
void main() {
  initializeJsonMapper(adapters: [
    JsonMapperAdapter(
      converters: {
        Enum: enumConverterNumeric,
      },
    )
  ]);

  var json = JsonMapper.serialize(MyClass());
  var myClass = JsonMapper.deserialize<MyClass>(json);
}
```

without the `enumConverterNumeric` it works fine though.

#

That's the error I get:

```shell
Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..1: -1
```

<details>
<summary>Full trace</summary>

```shell
E/flutter ( 4930): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..1: -1
E/flutter ( 4930): #0      List.[] (dart:core-patch/array.dart:191:52)
E/flutter ( 4930): #1      EnumConverterNumeric.fromJSON (package:dart_json_mapper/src/model/converters.dart:272:42)
E/flutter ( 4930): #2      ConstEnumConverterNumeric.fromJSON (package:dart_json_mapper/src/model/converters.dart:249:29)
E/flutter ( 4930): #3      JsonMapper._getConvertedValue (package:dart_json_mapper/src/mapper.dart:378:25)
E/flutter ( 4930): #4      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:835:11)
E/flutter ( 4930): #5      JsonMapper._deserializeObject.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:921:22)
E/flutter ( 4930): #6      JsonMapper._enumeratePublicProperties (package:dart_json_mapper/src/mapper.dart:478:14)
E/flutter ( 4930): #7      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:885:5)
E/flutter ( 4930): #8      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:58:21)
E/flutter ( 4930): #9      main (package:redacted/main.dart:36:28)
E/flutter ( 4930): #10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 4930): #11     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 4930): #12     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 4930): #13     _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 4930): #14     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 4930): #15     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 4930): #16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 4930): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```
</details>

** This is not a problem for me right now (I've just stumbled upon this while investigating #117), and I'm no even sure this is actually a problem (might be intentional?), as I didn't really found anything about this in the docs I thought it could be a bug. :)

**Comment by k-paxian** [comment]
Absolutely reasonable, the more edge cases will be covered the better :smile:
