### ISSUE TITLE
How to define a BaseResponse<T>?，Is it achievable？

### ISSUE THREAD

**Issue by iDevOrz** [k-paxian/dart-json-mapper#124]
## My Code

```dart
@jsonSerializable
class BaseResponse<T> {
  int code;
  T data;
  BaseResponse(this.code, this.data);
}
```

```dart
@jsonSerializable
class HomePageData{
    List<HomeTaskData> data = [];
    int? totalCount;
    int? unreadCount;
}

@jsonSerializable
class HomeTaskData {
    // some property and constructor
}
```
## Use:
```dart
//The value is a map response from Dio network Lib;
BaseResponse<HomePageData>? info =
            JsonMapper.fromMap<BaseResponse<HomePageData>>(value);
```

## Error:

```shell
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
#0      ListIterable.first (dart:_internal/iterable.dart:49:22)
#1      MapConverter.fromJSON.<anonymous closure> (package:dart_json_mapper/src/model/converters.dart:392:58)
#2      MapMixin.map (dart:collection/maps.dart:170:28)
#3      MapConverter.fromJSON (package:dart_json_mapper/src/model/converters.dart:391:25)
#4      JsonMapper._getConvertedValue (package:dart_json_mapper/src/mapper.dart:406:25)
#5      JsonMapper._deserializeObject.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:971:13)
#6      JsonMapper._enumeratePublicProperties (package:dart_json_mapper/src/mapper.dart:506:14)
#7      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:927:5)
#8      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:59:21)
#9      JsonMapper.fromMap (package:dart_json_mapper/src/mapper.dart:79:7)
#10     _HomeJobListState._getJobList.<anonymous closure> (package:app/pages/home/HomeJobList.dart:233:24)
#11     _rootRunUnary (dart:async/zone.dart:1362:47)
#12     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:539:5)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:254:13)
#18     DioManager._requstHttp (package:app/api/DioManager.dart)

```

**Comment by k-paxian** [comment]
https://www.github.com/k-paxian/dart-json-mapper/tree/master/mapper%2Ftest%2Ftest.generics.dart

**Comment by iDevOrz** [comment]
Thanks👍
