### ISSUE TITLE
Unhandled exception when deserializing a null list.

### ISSUE THREAD

**Issue by schultek** [k-paxian/dart-json-mapper#125]
Please see [this example](https://gist.github.com/schultek/e0d376122955a2f9d6b6fac25433b483).

There is an exception when trying to deserialize a List property that is null.

The output from the example above is:

```dart
{
 "model": "tesla",
 "miles": 1000,
 "passengers": [
  "Tom",
  "Anna"
 ]
}
Car{model: tesla, miles: 1000, passengers: [Tom, Anna]}
{
 "model": "tesla",
 "miles": null,
 "passengers": [
  "Tom",
  "Anna"
 ]
}
Car{model: tesla, miles: null, passengers: [Tom, Anna]}
{
 "model": "tesla",
 "miles": 1000,
 "passengers": null
}
Unhandled exception:
NoSuchMethodError: The method 'cast' was called on null.
Receiver: null
Tried calling: cast<String>()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      dartCoreAdapter.<anonymous closure> (package:dart_json_mapper/src/model/adapters.dart:82:44)
#2      JsonMapper._applyValueDecorator (package:dart_json_mapper/src/mapper.dart:432:47)
#3      JsonMapper._deserializeObject.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:979:22)
#4      JsonMapper._enumeratePublicProperties (package:dart_json_mapper/src/mapper.dart:506:14)
#5      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:927:5)
#6      JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:59:21)
#7      main (package:tesst/main.dart:37:20)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

It fails in the generated value decorator for any list type:

```dart
valueDecorators: {
    typeOf<List<x0.Car>>(): (value) => value.cast<x0.Car>(),
}
````

When value is null, the call to `.cast' throws. 

An easy fix is to just change the generated value decorators to `(value) => value?.cast<...>()`. But maybe a more robust solution is to check for null values before calling any value decorators [here](https://github.com/k-paxian/dart-json-mapper/blob/4fe16843650d2308699b00ae5126cf343ddb5d42/mapper/lib/src/mapper.dart#L436-L444).

**Comment by k-paxian** [comment]
Thank you for pointing this out 👍 should be ok now
