### ISSUE TITLE
dart-json-mapper is closing web socket

### ISSUE THREAD

**Issue by qbait** [k-paxian/dart-json-mapper#142]
I replaced `JsonSerialisable` with `dart-json-mapper` because I like that's a more clean package. However, I'm facing the issue when using it with websockets

```dart
  void _initSocket() {
    _socket.onOpen(() {
      _socket.send(JsonMapper.serialize(_subscriptionRequest));
    });

    _socket.onMessage((data) async {
      try {
        final newItem = JsonMapper.deserialize<SubscriptionItem>(data);

        debugPrint('newItem = $newItem');
      } catch (e) {
        debugPrint('Unsupported type for: $data, error: $e');
      }
    });

    _socket.onError((e) {
      snackbar('error called: ${e.message}');
    });

    _socket.connect();
  }
```

The error is related to closed Socket
```
E/flutter (12673): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: SocketException: Reading from a closed socket
E/flutter (12673): #0      _RawSecureSocket.read (dart:io/secure_socket.dart:662:7)
E/flutter (12673): #1      _Socket._onData (dart:io-patch/socket_patch.dart:2159:28)
E/flutter (12673): #2      _rootRunUnary (dart:async/zone.dart:1362:47)
E/flutter (12673): #3      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
E/flutter (12673): #4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1170:7)
E/flutter (12673): #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (12673): #6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (12673): #7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
E/flutter (12673): #8      _StreamController._add (dart:async/stream_controller.dart:607:7)
E/flutter (12673): #9      _StreamController.add (dart:async/stream_controller.dart:554:5)
E/flutter (12673): #10     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
E/flutter (12673): #11     _rootRun (dart:async/zone.dart:1346:47)
E/flutter (12673): #12     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (12673): #13     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (12673): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (12673): #15     _rootRun (dart:async/zone.dart:1354:13)
E/flutter (12673): #16     _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (12673): #17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1186:23)
E/flutter (12673): #18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (12673): #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
E/flutter (12673): #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
E/flutter (12673): #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
E/flutter (12673): 
```

Normally, I would suspect that's the problem with websockets, but with `JsonSerialisable` the same code works without a problem. That's why I think the issue is in `dart-json-mapper`.

Maybe it takes too much memory, or I should run it in solate or sth?

**Comment by k-paxian** [comment]
Yeah, it looks like running it in isolate will be a stable in terms of performance and non blocking main isolate. Like referenced [here](https://github.com/k-paxian/dart-json-mapper/issues/141) Please let me know all the details you'll run over this, ideally I'm looking for a stable piece of code with the sockets to build a unit test on top of it. Your input really valuable thank you for raising this 👍
