### ISSUE TITLE
Update version to 2.1.12 end with failed

### ISSUE THREAD

**Issue by rmasarovic** [k-paxian/dart-json-mapper#163]
Hi when i run build_runner build --delete-conflicting-outputs  and have version 2.1.3 and json_serializable:4.1.4 everything work.
When i update library to 2.1.12 and json_serializable:5.0.2 then this command  run build_runner build --delete-conflicting-outputs
end with this fail 

[   +5 ms] pub finished with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:391:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:247:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
           
           
[  +91 ms] ensureAnalyticsSent: 89ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

and i find this news log [SEVERE] dart_json_mapper:dart_json_mapper on lib/main.dart (cached):
`reflectedTypeArguments` where an actual type argument (possibly nested) is int Function(dynamic, dynamic)

any idea where is problem?

**Comment by k-paxian** [comment]
I'm pretty sure this issue is not related to `dart-json-mapper`

Here is the tests project having  (latest) `2.1.12` dart-json-mapper and `json_serializable:5.0.0`
https://github.com/k-paxian/dart-json-mapper/blob/master/perf-test/pubspec.yaml
successful build https://github.com/k-paxian/dart-json-mapper/runs/3784053525?check_suite_focus=true
