### ISSUE TITLE
Can't convert List<Cart>

### ISSUE THREAD

**Issue by VNAPNIC** [k-paxian/dart-json-mapper#17]
// Deserialize
`  print(JsonMapper.deserialize<Person>(personJson));`

print to:
```
Unhandled exception:
type List<dynamic> is not a subtype of type List<Car> of 'value'
#0      _data.<anonymous closure> (file:///E:/Flutter/dart-json-mapper-master/example/example.reflectable.dart:519:61)
#1      _InstanceMirrorImpl.invokeSetter (package:reflectable/src/reflectable_builder_based.dart:346:20)
#2      JsonMapper.deserializeObject.<anonymous closure> (package:dart_json_mapper/json_mapper.dart:523:12)
#3      JsonMapper.enumeratePublicFields (package:dart_json_mapper/json_mapper.dart:296:14)
#4      JsonMapper.deserializeObject (package:dart_json_mapper/json_mapper.dart:502:5)
#5      JsonMapper.deserialize (package:dart_json_mapper/json_mapper.dart:59:21)
#6      main (file:///E:/Flutter/dart-json-mapper-master/example/example.dart:101:20)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by k-paxian** [comment]
Sorry pal, have no idea what are you talking about.
"Cart"? show me the whole code if you want help

**Comment by VNAPNIC** [comment]
I used your example, but when I ran it and it error

https://github.com/k-paxian/dart-json-mapper/blob/master/example/example.dart

**Comment by k-paxian** [comment]
Just throw in this lines before deserialization:
```
  // Because Person has a custom list List<Car>, we have to provide value cast decorator for it
  // to be able to Deserialize
  final iterableCarDecorator = (value) => value.cast<Car>();
  JsonMapper.registerValueDecorator<List<Car>>(iterableCarDecorator);

  // Serialize
  print(JsonMapper.serialize(Person()));

  // Deserialize
  print(JsonMapper.deserialize<Person>(personJson));
```

**Comment by VNAPNIC** [comment]
woo  thank u,  I think u should update the example

**Comment by k-paxian** [comment]
Absolutely! I'll do that thanks to your attention, documentation is going better.

**Comment by VNAPNIC** [comment]
I think if u remove the registerValueDecorator, well it great :)

**Comment by k-paxian** [comment]
I would love to get rid of it myself,
[https://github.com/k-paxian/dart-json-mapper#iterable-based-types-handling](here) is the explanation of why it is like that. Dart language is not allowing another workaround for this case.
