### ISSUE TITLE
Intermittent build_runner failure: "Invalid argument(s): Missing library"

### ISSUE THREAD

**Issue by matt-hall-zory** [k-paxian/dart-json-mapper#223]
Have been struggling with running build_runner the last few weeks (after recent flutter update).  Sometimes it works, most of the time it doesn't. I've been playing around with packages the last four hours. I have already reported this to dart-lang (https://github.com/dart-lang/build/issues/3657), but build_runner is complaining about dart_json_mapper.

```
Flutter 3.19.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 68bfaea224 (4 days ago) • 2024-03-20 15:36:31 -0700
Engine • revision a5c24f538d
Tools • Dart 3.3.2 • DevTools 2.31.1
```

Build runner --verbose output in details. (truncated due to length)

<details>

```

[INFO] Generating build script...
[INFO] Generating build script completed, took 172ms

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 83ms

[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 861ms

[INFO] Running build...
[INFO] Running build completed, took 19ms

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 70ms

[SEVERE] dart_json_mapper on lib/main_preview.dart (cached):

Invalid argument(s): Missing library: package:zory/providers.dart
Libraries: [dart:async, dart:collection, dart:convert, dart:core, dart:developer, dart:ffi, dart:_http, dart:io, dart:isolate, dart:math, dart:nativewrappers, dart:typed_data, dart:_internal, dart:ui, package:reflectable/mirrors.dart, package:reflectable/src/reflectable_class_constants.dart, package:reflectable/src/encoding_constants.dart, package:reflectable/src/incompleteness.dart, package:reflectable/capability.dart, package:reflectable/reflectable.dart, package:reflectable/src/reflectable_base.dart, package:reflectable/src/reflectable_builder_based.dart, package:dart_json_mapper/src/model/value_decorators.dart, package:meta/meta_meta.dart, package:dart_json_mapper/src/identifier_casing.dart, package:collection/src/utils.dart, package:collection/src/algorithms.dart, package:collection/src/empty_unmodifiable_set.dart, package:collection/src/unmodifiable_wrappers.dart, 

...truncated...

package:firebase_auth_platform_interface/src/user_info.dart, package:package_info_plus_platform_interface/method_channel_package_info.dart, package:package_info_plus_platform_interface/package_info_platform_interface.dart, package:package_info_plus/package_info_plus.dart, package:zory/services/version_update_service.dart, package:package_info_plus/src/package_info_plus_linux.dart, package:package_info_plus/src/package_info_plus_windows.dart, package:in_app_purchase_android/src/channel.dart, package:in_app_purchase_storekit/src/channel.dart, package:in_app_purchase_storekit/src/messages.g.dart, package:in_app_purchase_storekit/src/store_kit_wrappers/sk_receipt_manager.dart, package:in_app_purchase_storekit/src/store_kit_wrappers/sk_storefront_wrapper.dart, package:shared_preferences_platform_interface/method_channel_shared_preferences.dart, package:shared_preferences_platform_interface/shared_preferences_platform_interface.dart, package:shared_preferences/shared_preferences.dart, package:zory/services/flutter_local_settings_service.dart, package:zory/services/local_asset_service.dart, package:url_launcher_windows/src/messages.g.dart, package:flutter/src/services/platform_views.dart, package:flutter_test/src/test_pointer.dart}][#0      LinkedElementFactory.removeLibraries (package:analyzer/src/summary2/linked_element_factory.dart:268:67)
#1      LibraryContext.remove (package:analyzer/src/dart/analysis/library_context.dart:274:20)
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer/src/dart/analysis/driver.dart:1952:22)
#3      AnalysisDriver._applyPendingFileChanges (package:analyzer/src/dart/analysis/driver.dart:1468:7)
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2318:16)
<asynchronous suspension>
]
[removeLibraries][uriSet: {}][#0      LinkedElementFactory.removeLibraries (package:analyzer/src/summary2/linked_element_factory.dart:268:67)
#1      LibraryContext.remove (package:analyzer/src/dart/analysis/library_context.dart:274:20)
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer/src/dart/analysis/driver.dart:1952:22)
#3      AnalysisDriver._applyPendingFileChanges (package:analyzer/src/dart/analysis/driver.dart:1468:7)
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2318:16)
<asynchronous suspension>
]
[load][targetLibrary: package:zory/onboarding/onboarding_screen.dart = /zory/lib/onboarding/onboarding_screen.dart]
[load][targetLibrary: package:zory/onboarding/onboarding_screen.dart = /zory/lib/onboarding/onboarding_screen.dart]
[load][targetLibrary: package:zory/main_preview.dart = /zory/lib/main_preview.dart]
[load][targetLibrary: package:zory/main_preview.dart = /zory/lib/main_preview.dart]
[removeLibraries][uriSet: {package:flutter_test/flutter_test.dart, package:firebase_core_platform_interface/src/pigeon/test_api.dart, package:firebase_core_platform_interface/firebase_core_platform_interface.dart, package:firebase_crashlytics/firebase_crashlytics.dart, package:zory/error_reporting.dart, package:zory/book/book_controller.dart, package:zory/reader/reader_screen.dart, package:zory/providers.dart, package:zory/main.dart, package:zory/account/settings_screen.dart, package:zory/app.dart, package:zory/account/account_controller.dart, package:zory/account/fcm_token.dart, package:zory/account/account_screen.dart, package:zory/explore/continue_reading_button.dart, package:zory/explore/explore_screen.dart, package:zory/explore/explore_unpublished_books.dart, package:zory/widget/book_cover_widget.dart, package:zory/reader/loading_screen.dart, package:zory/category/category_books_sliver_grid.dart, package:zory/category/category_screen.dart, package:zory/author/author_book_list.dart, package:zory/author/author_screen.dart, package:zory/explore/explore_library_wrap.dart, package:zory/explore/explore_beta_books.dart, package:zory/book/chapters_screen.dart, package:zory/book/book_screen.dart, package:zory/dialogs/spice_dialog.dart, package:zory/shelf/shelf_screen.dart, package:zory/routes/onboarding_route_guard.dart, package:zory/routes/auto_router.dart, package:zory/home_bar/home_bar_controller.dart, package:zory/services/firebase_account_service.dart, package:zory/extensions/snack_bar.dart, package:zory/services/firebase_remote_notifications_service.dart, package:zory/explore/explore_admin_drawer.dart, package:zory/services/flutter_local_notifications_service.dart, package:zory/dialogs/show_dialog_global.dart, package:zory/services/purchase_service_apple.dart, package:zory/services/purchase_service_common.dart, package:zory/services/purchase_service_google.dart, package:zory/services/purchase_service_staff.dart, package:zory/reader/reader_screen_controller.dart, package:zory/reader/reader_action_button.dart, package:zory/reader/reader_paragraph.dart, package:zory/reader/story_service.dart, package:zory/reader/reader_paragraph_widget.dart, package:zory/reader/paged_story_widget.dart, package:zory/reader/scroll_story_widget.dart, package:zory/reader/paragraph_choice_animated.dart, package:zory/reader/paragraph_end_animated.dart, package:zory/reader/paginate_paragraphs.dart, package:zory/reader/choice_button.dart, package:zory/store/purchase_dialog_overlay.dart, package:zory/reader/reader_app_bar.dart, package:zory/reader/variable_inspector.dart, package:zory/routes/preview_reader_router.dart, package:zory/dialogs/need_more_currency_dialog.dart, package:zory/store/store_item_button.dart, package:zory/store/store_screen.dart, package:zory/store/free_currency_button.dart, package:zory/category/category_card.dart, package:zory/category/category_button.dart, package:zory/category/category_header.dart, package:zory/auth/auth_screen.dart, package:zory/auth/onboarding_signin_screen.dart, package:zory/auth/account_sign_up_screen.dart, package:zory/auth/account_sign_in_screen.dart, package:zory/auth/email_password_form.dart, package:zory/home_bar/home_bar_screen.dart, package:zory/auth/reader_sign_in_screen.dart, package:zory/explore/explore_carousel.dart, package:zory/new/new_screen.dart, package:zory/new/new_book_card.dart, package:zory/shelf/shelf_filter.dart, package:zory/shelf/shelf_tutorial.dart, package:zory/account/delete_account_screen.dart, package:zory/account/confirm_delete_account_screen.dart, package:zory/account/account_details_screen.dart, package:zory/store/free_currency_info.dart, package:zory/onboarding/onboarding_screen.dart, package:zory/preview_reader_app.dart, package:zory/main_preview.dart, package:firebase_core/firebase_core.dart, package:firebase_crashlytics_platform_interface/src/method_channel/method_channel_crashlytics.dart, package:firebase_crashlytics_platform_interface/firebase_crashlytics_platform_interface.dart, package:firebase_crashlytics_platform_interface/src/platform_interface/platform_interface_crashlytics.dart, package:firebase_crashlytics_platform_interface/src/method_channel/utils/exception.dart, package:_flutterfire_internals/_flutterfire_internals.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_load_bundle_task.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_query_snapshot.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_collection_reference.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_change.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_query.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_aggregate_query.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_transaction.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_write_batch.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_aggregate_query.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_aggregate_query_snapshot.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_collection_reference.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_change.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_reference.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_document_snapshot.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_field_value_factory.dart, package:cloud_firestore_platform_interface/src/method_channel/method_channel_field_value_factory.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_firestore.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_load_bundle_task_snapshot.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_query_snapshot.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_transaction.dart, package:cloud_firestore_platform_interface/src/platform_interface/platform_interface_write_batch.dart, package:cloud_firestore_platform_interface/src/platform_interface/utils/load_bundle_task_state.dart, package:cloud_firestore_platform_interface/src/get_options.dart, package:cloud_firestore_platform_interface/src/method_channel/utils/exception.dart, package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart, package:firebase_auth_platform_interface/src/platform_interface/platform_interface_firebase_auth.dart, package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart, package:firebase_auth/firebase_auth.dart, package:zory/services/auth_service.dart, package:zory/auth/auth_screen_controller.dart, package:zory/auth/reader_sign_in_screen_controller.dart, package:zory/services/firebase_auth_service.dart, package:zory/services/writer_account_service.dart, package:firebase_auth_platform_interface/src/firebase_auth_multi_factor_exception.dart, package:firebase_auth_platform_interface/src/platform_interface/platform_interface_confirmation_result.dart, package:firebase_auth_platform_interface/src/method_channel/method_channel_multi_factor.dart, package:firebase_auth_platform_interface/src/method_channel/method_channel_user_credential.dart, package:firebase_auth_platform_interface/src/method_channel/method_channel_user.dart, package:firebase_auth_platform_interface/src/method_channel/utils/exception.dart, package:firebase_auth_platform_interface/src/platform_interface/platform_interface_multi_factor.dart, package:firebase_auth_platform_interface/src/method_channel/utils/convert_auth_provider.dart, package:firebase_auth_platform_interface/src/method_channel/utils/pigeon_helper.dart, package:firebase_auth_platform_interface/src/platform_interface/platform_interface_recaptcha_verifier_factory.dart, package:firebase_auth_platform_interface/src/platform_interface/platform_interface_user.dart, package:firebase_auth_platform_interface/src/platform_interface/platform_interface_user_credential.dart, package:firebase_auth_platform_interface/src/providers/apple_auth.dart, package:firebase_auth_platform_interface/src/providers/email_auth.dart, package:firebase_auth_platform_interface/src/providers/facebook_auth.dart, package:firebase_auth_platform_interface/src/providers/game_center_auth.dart, package:firebase_auth_platform_interface/src/providers/github_auth.dart, package:firebase_auth_platform_interface/src/providers/google_auth.dart, package:firebase_auth_platform_interface/src/providers/microsoft_auth.dart, package:firebase_auth_platform_interface/src/providers/oauth.dart, package:firebase_auth_platform_interface/src/providers/phone_auth.dart, package:firebase_auth_platform_interface/src/types.dart, package:firebase_auth_platform_interface/src/providers/twitter_auth.dart, package:firebase_auth_platform_interface/src/providers/yahoo_auth.dart, package:firebase_auth_platform_interface/src/providers/play_games_auth.dart, package:firebase_messaging_platform_interface/src/method_channel/utils/exception.dart, package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart, package:firebase_messaging_platform_interface/src/platform_interface/platform_interface_messaging.dart, package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart, package:firebase_messaging/firebase_messaging.dart, package:zory/services/remote_notifications_service.dart, package:firebase_messaging_platform_interface/src/utils.dart, package:firebase_messaging_platform_interface/src/remote_notification.dart, package:firebase_messaging_platform_interface/src/notification_settings.dart, package:firebase_messaging_platform_interface/src/types.dart, package:firebase_messaging_platform_interface/src/remote_message.dart, package:firebase_analytics_platform_interface/src/method_channel/utils/exception.dart, package:firebase_analytics_platform_interface/src/method_channel/method_channel_firebase_analytics.dart, package:firebase_analytics_platform_interface/firebase_analytics_platform_interface.dart, package:firebase_analytics/firebase_analytics.dart, package:zory/services/firebase_analytics_service.dart, package:firebase_analytics/observer.dart, package:firebase_analytics_platform_interface/src/platform_interface/platform_interface_firebase_analytics.dart, package:_flutterfire_internals/src/exception.dart, package:cloud_functions/cloud_functions.dart, package:cloud_functions_platform_interface/src/firebase_functions_exception.dart, package:cloud_functions_platform_interface/cloud_functions_platform_interface.dart, package:cloud_functions_platform_interface/src/platform_interface/platform_interface_firebase_functions.dart, package:cloud_functions_platform_interface/src/method_channel/method_channel_firebase_functions.dart, package:cloud_functions_platform_interface/src/method_channel/method_channel_https_callable.dart, package:cloud_functions_platform_interface/src/method_channel/utils/exception.dart, package:cloud_functions_platform_interface/src/platform_interface/platform_interface_https_callable.dart, package:firebase_auth_platform_interface/src/firebase_auth_exception.dart, package:zory/firebase_options.dart, package:zory/firebase_options_preview_reader.dart, package:firebase_core_platform_interface/src/pigeon/mocks.dart}][#0      LinkedElementFactory.removeLibraries (package:analyzer/src/summary2/linked_element_factory.dart:268:67)
#1      LibraryContext.remove (package:analyzer/src/dart/analysis/library_context.dart:274:20)
#2      AnalysisDriver._removePotentiallyAffectedLibraries (package:analyzer/src/dart/analysis/driver.dart:1952:22)
#3      AnalysisDriver._applyPendingFileChanges (package:analyzer/src/dart/analysis/driver.dart:1468:7)
#4      AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2318:16)
<asynchronous suspension>
]

[SEVERE] Failed after 97ms

```

</details>

**Comment by k-paxian** [comment]
Sad to see that. Unfortunately it's not telling me literally anything useful. If it is possible to isolate the issue on a clean repo, I'll be glad to look at it.

**Comment by matt-hall-zory** [comment]
Thanks for checking, I wasn't sure if I was missing something obvious.

**Comment by matt-hall-zory** [comment]
I found a workaround.
Each time I get the "missing library" error I add a comment to the file then re-run build_runner. After running a few times, touching each file with an error I'm able to complete the build_runner process. I then remove the comments and commit.

**Comment by k-paxian** [comment]
Are you running a build runner in a watch mode?

**Comment by matt-hall-zory** [comment]
No, I run it manually.
