### ISSUE TITLE
Flutter for Web: Dynamic call with too many arguments. Arguments: [Instance of 'NativeJavaScriptObject'

### ISSUE THREAD

**Issue by petermcneil** [k-paxian/dart-json-mapper#77]
This is a flutter related bug. I've just tried to run my app on Chrome and load in JSON file, but I am encountering an error. It works fine for both Android and iOS. 

This is causing the app to not be able to parse any JSON in the web app. Is there a problem with the way I set this up? Or is it simply the fact the package isn't updated to Flutter 1.20?

### Error Stacktrace
```sh
Error: NoSuchMethodError: ''
Dynamic call with too many arguments. Expected: 0 Actual: 1
Receiver: Instance of '({dynamic answer, dynamic markingSteps, dynamic question, dynamic total}) => QuizQuestion'
Arguments: [Instance of 'NativeJavaScriptObject', question: Instance of 'TextQuestion', answer: Instance of 'TextAnswer', total: 1, markingSteps: 1]
    at Object.throw_ [as throw] (http://localhost:56001/dart_sdk.js:4322:11)
    at Object.defaultNoSuchMethod (http://localhost:56001/dart_sdk.js:4760:15)
    at Function.noSuchMethod (http://localhost:56001/dart_sdk.js:5815:19)
    at Object.noSuchMethod (http://localhost:56001/dart_sdk.js:4756:30)
    at callNSM (http://localhost:56001/dart_sdk.js:4495:19)
    at Object._checkAndCall (http://localhost:56001/dart_sdk.js:4534:12)
    at Object.dcall (http://localhost:56001/dart_sdk.js:4537:17)
    at Function.apply (http://localhost:56001/dart_sdk.js:123788:21)
    at reflectable_builder_based.NonGenericClassMirrorImpl.new.newInstance (http://localhost:56001/packages/reflectable/src/reflectable_base.dart.lib.js:896:28)
    at mapper.JsonMapper._internal.deserializeObject (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:754:108)
    at MappedListIterable.new.<anonymous> (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:711:85)
    at MappedListIterable.new.elementAt (http://localhost:56001/dart_sdk.js:21166:25)
    at ListIterator.new.moveNext (http://localhost:56001/dart_sdk.js:20960:55)
    at JsIterator.next (http://localhost:56001/dart_sdk.js:5989:21)
    at Function.from (http://localhost:56001/dart_sdk.js:43521:20)
    at Function.of (http://localhost:56001/dart_sdk.js:43536:30)
    at MappedListIterable.new.toList (http://localhost:56001/dart_sdk.js:20765:26)
    at mapper.JsonMapper._internal.deserializeIterable (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:711:236)
    at mapper.JsonMapper._internal.deserializeObject (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:725:33)
    at http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:574:22
    at Array.[dartx.forEach] (http://localhost:56001/dart_sdk.js:14691:11)
    at mapper.JsonMapper._internal.enumerateConstructorParameters (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:556:40)
    at mapper.JsonMapper._internal.getNamedArguments (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:595:12)
    at mapper.JsonMapper._internal.deserializeObject (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:753:33)
    at MappedListIterable.new.<anonymous> (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:711:85)
    at MappedListIterable.new.elementAt (http://localhost:56001/dart_sdk.js:21166:25)
    at ListIterator.new.moveNext (http://localhost:56001/dart_sdk.js:20960:55)
    at JsIterator.next (http://localhost:56001/dart_sdk.js:5989:21)
    at Function.from (http://localhost:56001/dart_sdk.js:43521:20)
    at Function.of (http://localhost:56001/dart_sdk.js:43536:30)
    at MappedListIterable.new.toList (http://localhost:56001/dart_sdk.js:20765:26)
    at mapper.JsonMapper._internal.deserializeIterable (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:711:236)
    at mapper.JsonMapper._internal.deserializeObject (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:725:33)
    at http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:574:22
    at Array.[dartx.forEach] (http://localhost:56001/dart_sdk.js:14691:11)
    at mapper.JsonMapper._internal.enumerateConstructorParameters (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:556:40)
    at mapper.JsonMapper._internal.getNamedArguments (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:595:12)
    at mapper.JsonMapper._internal.deserializeObject (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:753:33)
    at Function.deserialize (http://localhost:56001/packages/dart_json_mapper/src/mapper.dart.lib.js:295:59)
    at user_db.InMemoryDb.new.init (http://localhost:56001/packages/qwiz/service/db/user_db.dart.lib.js:86:38)
    at init.next (<anonymous>)
    at http://localhost:56001/dart_sdk.js:37211:33
    at _RootZone.runUnary (http://localhost:56001/dart_sdk.js:37065:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:56001/dart_sdk.js:32049:29)
    at handleValueCallback (http://localhost:56001/dart_sdk.js:32596:49)
    at Function._propagateToListeners (http://localhost:56001/dart_sdk.js:32634:17)
    at _Future.new.[_completeWithValue] (http://localhost:56001/dart_sdk.js:32477:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:56001/dart_sdk.js:32499:35)
    at Object._microtaskLoop (http://localhost:56001/dart_sdk.js:37326:13)
    at _startMicrotaskLoop (http://localhost:56001/dart_sdk.js:37332:13)
    at http://localhost:56001/dart_sdk.js:32851:9

```

### Flutter doctor output
```sh
[✓] Flutter (Channel beta, 1.20.0, on Mac OS X 10.15.5 19F96, locale en-GB)
    • Flutter version 1.20.0 at $HOME/flutter/flutter
    • Framework revision 916c3ac648 (7 days ago), 2020-08-01 09:01:12 -0700
    • Engine revision d6ee1499c2
    • Dart version 2.9.0 (build 2.9.0-21.10.beta)

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105
```

**Comment by k-paxian** [comment]
Hey Peter, thank you for letting me know. It seems to me as an https://github.com/google/reflectable.dart library is not up to date with the latest Dart + Flutter dependencies. Once it'll be updated I'm sure it should be resolved.

**Comment by CiriousJoker** [comment]
Holy shit I didn't expect anyone to have this exact error message. I thought I had some exotic data structure that wasn't compatible with dart2js or smth.

**Comment by k-paxian** [comment]
Can someone re-validate this with the latest mapper version `1.6.3` ?

**Comment by k-paxian** [comment]
closed due to no response

**Comment by s6o** [comment]
This seems still to be an issue with dart_json_mapper 1.7.6 for Flutter web.

As work-around the kIsWeb constant can be checked for "classical decoding". https://github.com/s6o/flutter-postgrest-todomvc/blob/4ad6a504bad29209c83b3f18db82882ea9490bec/app/lib/api.dart#L76

```
Flutter 1.25.0-8.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b0a2299859 (4 days ago) • 2021-01-05 12:34:13 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
```

```
NoSuchMethodError: ''
Dynamic call with too many arguments. Expected: 0 Actual: 1
Receiver: Instance of '({dynamic done, dynamic doneAt, dynamic due, dynamic id, dynamic task}) => Todo'
Arguments: [Instance of 'NativeJavaScriptObject', task: "Start training tomorrow", due: Instance of 'DateTime', done: false, id: 1, doneAt: null]
Error: Expected a value of type 'Error', but got one of type 'NoSuchMethodError'
    at Object.throw_ [as throw] (http://localhost:60657/dart_sdk.js:4354:11)
    at Object.castError (http://localhost:60657/dart_sdk.js:4325:15)
    at Object.cast [as as] (http://localhost:60657/dart_sdk.js:4641:17)
    at dart.LegacyType.new.as (http://localhost:60657/dart_sdk.js:6232:60)
    at login._LoginPageState.new.<anonymous> (http://localhost:60657/packages/todomvc/login.dart.lib.js:592:132)
    at Generator.throw (<anonymous>)
    at http://localhost:60657/dart_sdk.js:38006:38
    at _RootZone.runBinary (http://localhost:60657/dart_sdk.js:37859:58)
    at _FutureListener.thenAwait.handleError (http://localhost:60657/dart_sdk.js:32827:48)
    at handleError (http://localhost:60657/dart_sdk.js:33379:51)
    at Function._propagateToListeners (http://localhost:60657/dart_sdk.js:33405:17)
    at _Future.new.[_completeWithValue] (http://localhost:60657/dart_sdk.js:33243:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60657/dart_sdk.js:33266:35)
    at Object._microtaskLoop (http://localhost:60657/dart_sdk.js:38115:13)
    at _startMicrotaskLoop (http://localhost:60657/dart_sdk.js:38121:13)
    at http://localhost:60657/dart_sdk.js:33618:9
```

**Comment by k-paxian** [comment]
```dart
const bool kIsWeb = identical(0, 0.0)
```

So basically we could mitigate this inhouse, that's a good thing 👍

**Comment by cedvdb** [comment]
Still an issue for me on   dart_json_mapper: ^1.7.12

**Comment by k-paxian** [comment]
@cedvdb Thank you for reporting this. Could you please provide more context on this, code sample you are running, it is AOT compiled? Debug version? Web? etc. 

I've tried to reproduce it with the latest flutter version. For Web I've got these results
* Compiled via AOT for the web chrome + With sound null safety 🔴 it's not running at all because of [JS obfuscation ](https://github.com/k-paxian/dart-json-mapper#known-limitations)
* Compiled via AOT/GIT Debug version for the web chrome w/o sound null safety 🟢 Everything works nice.

**Comment by cedvdb** [comment]
I made a quick repo for a repro https://github.com/cedvdb/failing-dart-json-mapper

**Comment by k-paxian** [comment]
Post mortem:

```dart
@jsonSerializable
class Test {
  final String a;

  Test({
    this.a,
  });
}

print(JsonMapper.fromMap<Test>({}).toString());
```

This should print out on the Web:

```
Instance of Test
```

Having named/optional arguments for the class `Test` constructor it's fine and 💚  for the Dart language.
But when this class is transpiled to Javascript, there are 🔴 support for named parameters, **only** positional arguments are supported there. So knowing that we could rephrase snippet above as

 ```dart
@jsonSerializable
class Test {
  final String a;

  const Test(this.a);
}

print(JsonMapper.fromMap<Test>({'a': 'b'}).a);
```

This should print out on the Web:

```
b
```

P.S. @cedvdb Thank you so much for taking your time and helping me to nail this one down 😄

**Comment by cedvdb** [comment]
This is a sizeable limitation. Is it from the reflectable package or only this one ? Javascript doesn't have named parameters but you can pass anything.

ie you can pass an assigned object:

```
class Test {
   a;
   Test(toAssign) {
     Object.assign(this, a);
   }
}

Test({ a: 3 });
```

I'm not sure that helps, as I have no idea where the javascript generation happen.

**Comment by k-paxian** [comment]
Well, I don't see it as a limitation at all, since those snippets should work as expected

```dart
@jsonSerializable
class Test {
  String a;

  Test({  this.a  });
}

print(JsonMapper.fromMap<Test>({'a': 'b'}).a); // this should print 'b'
```

```dart
@jsonSerializable
class Test {
 final String a;

 const Test(this.a);
}

print(JsonMapper.fromMap<Test>({'a': 'b'}).a); // this should print 'b'
```

* you are able to use named parameters to constructor ✔️ 
* you are able to create Dart immutable class ✔️ 
* no exception thrown by mapper code ✔️ 
* works same way on all platforms ✔️ 


The problem 🔴  in combination of final fields vs optional constructor parameters:
```dart
@jsonSerializable
class Test {
  final String a;

  Test({  this.a  });
}
```
What this class tells us?

you can pass **optional** named parameter to the **final** class field, right? Final means you can set it only once, this means if you omit constructor parameters at all, field `a` will be `null` forever? are we **OK** with this? I guess not really

Transpilation to JS is done via [dart2js](https://dart.dev/tools/dart2js#helping-dart2js-generate-efficient-code) and there are best practices list provided, including common sense.

Can you expand on what do you feel is a limitation?

**Comment by cedvdb** [comment]
> are we OK with this ?  I guess not really

Hum I'll argue that prior to null safety it should be ok, it's what optional named parameters are for.
Anyway, I feel like null safety will resolve this.
