### ISSUE TITLE
Cyclic error in JSON stringify when using a template 

### ISSUE THREAD

**Issue by moneer-muntazah** [k-paxian/dart-json-mapper#80]
Hi k-paxian, and everyone else,

Why do I get the following exception

```
Unhandled exception:
Cyclic error in JSON stringify
#0      _JsonStringifier._checkCycle (dart:convert/json.dart:616:9)
#1      _JsonStringifier.writeJsonValue (dart:convert/json.dart:683:7)
#2      _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#3      _JsonStringifier.writeMap (dart:convert/json.dart:730:7)
#4      _JsonStringifier.writeJsonValue (dart:convert/json.dart:685:21)
#5      _JsonStringifier.writeObject (dart:convert/json.dart:640:9)
#6      _JsonStringStringifier.printOn (dart:convert/json.dart:836:17)
#7      _JsonStringStringifier.stringify (dart:convert/json.dart:821:5)
#8      JsonEncoder.convert (dart:convert/json.dart:257:30)
#9      JsonMapper.serialize (package:dart_json_mapper/src/mapper.dart:38:10)
#10     JsonMapper.toJson (package:dart_json_mapper/src/mapper.dart:29:12)
#11     main (package:templateerror/main.dart:27:18)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

when I run 

```dart
import 'package:dart_json_mapper/dart_json_mapper.dart'
    show JsonMapper, jsonSerializable, SerializationOptions;

import 'main.reflectable.dart' show initializeReflectable;

@jsonSerializable
class Address {
  
}

@jsonSerializable
class User {
  int id;
  Address addresses;
}

void main() {
  initializeReflectable();

  User user = User()
    ..id = 42
    ..addresses = Address();


  Map<String, dynamic> template = {};

  String json =
      JsonMapper.toJson(user, SerializationOptions(template: template));

  print(json);
}

```

I noticed that if I remove the template the exception goes away.

**Comment by k-paxian** [comment]
@moneer-muntazah  Thank you so much for finding edge cases ❤️ 
Fixed as of `1.5.22`
