### ISSUE TITLE
Bad state: No element when trying to deserialize an enum

### ISSUE THREAD

**Issue by Norbert515** [k-paxian/dart-json-mapper#93]
Relevant line:

```dart
    var result = JsonMapper.fromMap<MyObject>(Map<String, dynamic>.from(theObject));
```

where 
```dart
class MyObject {

  // Has an enum
}
```

From debugging it seems like it is trying to get a constructor for the enum but it isn't able to find one. Any ideas?

Might be related to:
https://github.com/k-paxian/dart-json-mapper/issues/92

Stacktrace:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: No element
#0      Iterable.firstWhere (dart:core/iterable.dart:578:5)
#1      ClassInfo.getJsonConstructor (package:dart_json_mapper/src/utils.dart:192:41)
#2      JsonMapper._enumerateConstructorParameters (package:dart_json_mapper/src/mapper.dart:496:36)
#3      JsonMapper._getNamedArguments (package:dart_json_mapper/src/mapper.dart:572:5)
#4      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:807:28)
#5      JsonMapper._enumerateConstructorParameters.<anonymous closure> (package:dart_json_mapper/src/mapper.dart:531:15)
#6      List.forEach (dart:core-patch/growable_array.dart:313:8)
#7      JsonMapper._enumerateConstructorParameters (package:dart_json_mapper/src/mapper.dart:500:29)
#8      JsonMapper._getNamedArguments (package:dart_json_mapper/src/mapper.dart:572:5)
#9      JsonMapper._deserializeObject (package:dart_json_mapper/src/mapper.dart:807:28)
#10     JsonMapper.deserialize (package:dart_json_mapper/src/mapper.dart:59:21)
#11     JsonMapper.fromMap (package:dart_json_mapper/src/mapper.dart:79:12)
```

**Comment by k-paxian** [comment]
Please add more details. Minimal reproducible code

**Comment by Norbert515** [comment]
I've tried to reproduce it with little luck. Was wondering if you had an idea form just looking it at - will try again!
