### ISSUE TITLE
"Reflectable has not been initialized."

### ISSUE THREAD

**Issue by safield** [k-paxian/dart-json-mapper#98]
I get the following exception throw when I try to call JsonMapper.deserialize<T>().

I followed the basic setup guide. So if I am missing some code, I suggest updating the setup guide.

```
_stackTrace:#0      data (package:reflectable/src/reflectable_builder_based.dart:177:5)
#1      data (package:reflectable/src/reflectable_builder_based.dart)
#2      ReflectableImpl.annotatedClasses (package:reflectable/src/reflectable_builder_based.dart:2596:9)
#3      new JsonMapper._internal (package:dart_json_mapper/src/mapper.dart:117:43)
#4      JsonMapper.instance (package:dart_json_mapper/src/mapper.dart:13:49)
#5      JsonMapper.instance (package:dart_json_mapper/src/mapper.dart)
#6      JsonMapper.serialize (package:dart_json_mapper/src/mapper.dart:42:37)
#7      UserModel.updateUserAssessment (package:sidekicktool/models/user_model.dart:257:20)
#8      _AssessmentScreenState.build.<anonymous closure> (package:sidekicktool/ui/AssessmentScreen.dart:98:69)
#9      _AssessmentScreenState.build.<anonymous closure> (package:sidekicktool/ui/AssessmentScreen.dart:91:22)
#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
#11     TapGestureRecognizer.handleTapUp (package:flutt...
message:"Reflectable has not been initialized.
Please make sure that the first action taken by your program
in `main` is to call `initial…"
hashCode:120932757
runtimeType:Type (StateError)
stackTrace:#0      data (package:reflectable/src/reflectable_builder_based.dart:177:5)
```

**Comment by k-paxian** [comment]
Please show your main.dart content.
You should call methods after initialize method.

**Comment by safield** [comment]
I have not modified my main.dart at all. I have definitely not called initializeJsonMapper() anywhere. I did not see anything about that in the getting started docs.

**Comment by k-paxian** [comment]
​>​ pub run build_runner watch --delete-conflicting-outputs
